version: '3'

services:

  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    volumes:
      - /home/hkovac/data:/var/www/html
    depends_on:
      - wp-fpm
    ports: 
      - "443:443"
    restart: always
    networks:
      - frontend

  wp-fpm:
    build: ./requirements/wordpress-fpm/
    container_name: wp-fpm
    volumes:
      - /home/hkovac/data/wordpress:/var/www/html/wordpress
    env_file:
      - .env
    tty: true
    stdin_open: true
    ports: 
      - "9000:9000"
    networks:
      - frontend
      - backend
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - /home/hkovac/data/db:/var/www/db
    tty: true
    stdin_open: true
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - backend
    restart: always

networks:
  frontend:
  backend: